services:
  vllm-worker:
    image: sidakalankam1103/self-hosted-llama-vllm-worker:v2
    container_name: vllm-worker
    restart: unless-stopped

    environment:
      MODEL_NAME: llama-3.1-8b-instruct
      MODEL_BUCKET: personal-llm-registry

    volumes:
      - /mnt/models:/models

    ports:
      - "8000:8000"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]